version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
	- "Microsoft.VisualStudio.Azure.Containers*
        - "Microsoft.EntityFrameworkCore*"
        - "Microsoft.AspNetCore*"
	- "Microsoft.NET.Test.*"
        - "xunit*"
	- AutoMapper
